name: telegram-sergiusens
version: 0.9.48
summary: Telegram desktop client
description: |
    Telegram is a popular messaging protocol with encryption and security as
    its key focus.

apps:
  telegram:
    command: telegram.sh -workdir $SNAP_USER_DATA -noupdate
    plugs: [unity7, network, network-bind]

parts:
  telegram:
    plugin: copy
    source: https://updates.tdesktop.com/tlinux/tsetup.0.9.48.tar.xz
    stage-packages:
        - xkb-data
    files:
        Telegram: bin/Telegram
  wrapper:
    plugin: copy
    files:
      telegram.sh: bin/telegram.sh
